### ISSUE TITLE
ps-tree < 1.1.1 has a deprecated dependency due to malicious code

### ISSUE THREAD

**Issue by estreiten** [foreversd/forever-monitor#163]
Hi! I know it may imply a huge version jump, but is it possible to use ps-tree >=1.1.1 on this module in order to update [forever](https://github.com/foreverjs/forever)?
It's the threat reported on the issue you fixed on ps-tree too: [indexzero/ps-tree#33](https://github.com/indexzero/ps-tree/issues/33)

Any info related will be appreciated, thanks!

**Comment by kibertoad** [comment]
@estreiten Unfortunately, plenty of tests fail after the update, so some effort is needed to make that happen. Any contributions in that direction would be most welcome :)

**Comment by ffflorian** [comment]
Locally tests were green so I created #191.
