### ISSUE TITLE
vulnerability in minimist

### ISSUE THREAD

**Issue by gaonkar18y** [foreversd/forever-monitor#193]
We get below vulnerability during npm audit

Package        minimist                                                     
Patched in     >=0.2.1 <1.0.0 || >=1.2.3                                    
Dependency of  forever-monitor                                              
Path           forever-monitor > broadway > nconf > optimist > minimist  

I can see that the version of 'broadway' is very old i.e "~0.3.6".

Can you please make required changes to fix this vulnerability.

Thanks in advance for any help.

**Comment by kibertoad** [comment]
Released in `forever-monitor` 3.0.2 and `forever` 3.0.3.
